version: "3"
services:
    #PHP Service
    sdi-madiun:
        container_name: sdi-madiun
        network_mode: host
        build:
            context: ./dockerconf
            args:
                uid: 1001
                user: tati
            dockerfile: Dockerfile
        image: "laravel-php-8.2"
        restart: unless-stopped
        tty: true
        environment:
            SERVICE_NAME: sdi-madiun
            SERVICE_TAGS: dev
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./dockerconf/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - sdi-madiun-network

    # Nginx Service
    sdi-madiun-nginx:
        container_name: sdi-madiun-nginx
        image: nginx:alpine
        restart: unless-stopped
        tty: true
        ports:
            - 8001:8001
        volumes:
            - ./:/var/www
            - ./dockerconf/nginx.app.conf:/etc/nginx/conf.d/app.conf
        networks:
            - sdi-madiun-network

